FROM csgo-metamod:latest

RUN  curl -O https://sm.alliedmods.net/smdrop/1.11/sourcemod-1.11.0-git6526-linux.tar.gz && \
     tar zxf sourcemod-1.11.0-git6526-linux.tar.gz -C $SRCDS_HOME/csgo && \
     rm sourcemod-1.11.0-git6526-linux.tar.gz
