FROM csgo-srcds:latest

RUN  curl -O https://mms.alliedmods.net/mmsdrop/1.11/mmsource-1.11.0-git1130-linux.tar.gz && \
     tar zxf mmsource-1.11.0-git1130-linux.tar.gz -C $SRCDS_HOME/csgo && \
     rm mmsource-1.11.0-git1130-linux.tar.gz
